confirmonquit: false
git:
  autofetch: true
  merging:
    manualcommit: false
  skiphookprefix: WIP
  paging:
    colorArg: always
gui:
  commitlength:
    show: true
  mouseevents: false
  scrollheight: 2
  scrollpastbottom: true
  showCommandLog: false
  theme:
    lightTheme: true
    activeBorderColor:
      - blue
      - bold
    inactiveBorderColor:
      - black
reporting: "off"
splashupdatesindex: 0
startuppopupversion: 1
keybinding:
  universal:
    quit-alt1: '<esc>'
