alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'
alias tmux='tmux -2'
alias vi='nvim'
alias vim='nvim'
alias lg='lazygit'
alias rg='ranger'
alias j='jobs'
# git
alias gs='git status'
alias ga='git add'
alias gcm='git commit -m'
alias ggpush='git push'
alias ggpull='git pull'
